src/components/layout/header.js
src/components/layout/menu.js
src/components/layout/sider.js
src/components/users/list.js
src/models/app.js
src/routes/app.js
src/routes/users.js

优化侧边栏导航刷新后依旧能展开选中当前地址的菜单项

---

src/components/users/list.js
src/routes/users.js

users-motion rc-tween-one 优化

---

package.json
src/index.html
src/index.js
src/router.js
webpack.config.js

hashHistory to browserHistory功能实现

hashHistory to browserHistory

---

src/components/common/TableBodyWrapper.js
src/components/users/list.js
src/routes/users.js

列表动画提取TableBodyWrapper.js组件，方面植入与移除

列表动画提取TableBodyWrapper.js组件

---

package.json
webpack.config.js

publicPath from webpack.config.js to package.json ，配置回归

publicPath from webpack.config.js to package.json

---

README.md

https://github.com/zuiidea/antd-admin.git

修改git clone

---

src/components/layout/main.less
src/components/layout/menu.js

fix menu style

---

package.json
src/components/skin.less

fix modal form

---

package.json

1. 去掉重复的 antd 依赖。
2. 补充 roadhog。

Fix devDeps

---

src/components/Search/Search.js

the variable named 'handeleSelectChange' seems not right.
turn `handeleSelectChange` to `handleSelectChange`
Hope  accept my advice, thanks

Search.js has a mistake var name

---

src/models/user.js

showModal return bug case Modal page display is null when update user info

showModal return bug

---

src/themes/index.less

https://github.com/ant-design/ant-design/issues/6833

No need customzied card style

---

src/models/app.js
src/routes/post/index.js
src/routes/user/index.js

升级dva@2.0的pr没有仔细测试，漏掉了部分代码，希望能尽快合并一下

fix bug#575

---

.gitignore

.gitignore 增加排除项

---

src/components/Layout/Menu.js
src/router.js

1、本地化
2、解决侧边栏收起时菜单图标悬浮下无菜单文字显示的问题

本地化和解决侧边栏收起时菜单图标悬浮下无菜单文字显示的问题

---

package.json

Update Echarts version

---

src/services/app.js
src/services/dashboard.js
src/services/login.js
src/services/menus.js
src/services/posts.js
src/services/user.js
src/services/users.js
src/services/weather.js

I think these services shouldn't be asynchronous functions. They already return a promise as a result of request function. And If don't use await expression should be better using regular functions.

remove unnecessary async functions

---

src/routes/user/index.js

refresh should on click the 「OK」button, not on the modal show.

refresh bug

---

package.json
src/pages/user/index.js
src/utils/config.js

In page user list, Operation choose update or remove error handleRefresh

:bug: fix remove and update user error handleRefresh

---

src/components/Layout/Sider.js

Fix [issue 992](https://github.com/zuiidea/antd-admin/issues/992)

:bug: fix bug sub menu Charts when collapsed
